"""
Django settings for cert_platform project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load environment variables from a .env file placed alongside manage.py
env_path = BASE_DIR / ".env"
if env_path.exists():
    with env_path.open() as f:
        for line in f:
            stripped = line.strip()
            # Skip comments and empty lines
            if not stripped or stripped.startswith("#"):
                continue
            if "=" not in stripped:
                continue
            key, value = stripped.split("=", 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-uwp5l!13-mfptif=dnjqxoi)of-thj@dodgl9k2%obfzu3-^pa",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() == "true"

ALLOWED_HOSTS = (
    [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]
    if not DEBUG
    else []
)

# CSRF Trusted Origins for admin panel
# Add your production domain here or via CSRF_TRUSTED_ORIGINS env variable
default_origins = "https://citsdigital.tech,https://www.citsdigital.tech,https://uncomfortable-karin-cits-free-9b96c27e.koyeb.app,http://127.0.0.1:8000,http://localhost:8000"
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", default_origins).split(",")
    if origin.strip()
]

# Session and CSRF cookie settings
# In production (HTTPS), these should be True. In development (HTTP), False.
SESSION_COOKIE_SECURE = not DEBUG  # True in production, False in development
CSRF_COOKIE_SECURE = not DEBUG  # True in production, False in development
SESSION_COOKIE_SAMESITE = 'Lax'  # Allows cookies to be sent with same-site requests
CSRF_COOKIE_SAMESITE = 'Lax'

ADMIN_PANEL_PASSWORD = os.environ.get("ADMIN_PANEL_PASSWORD", "Prakash10")
ADMIN_TOKEN_TTL_SECONDS = int(os.environ.get("ADMIN_TOKEN_TTL_SECONDS", 60 * 60 * 12))

# SMTP Configuration for Gmail
SMTP_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USERNAME = os.environ.get("SMTP_USERNAME")
SMTP_PASSWORD = os.environ.get("SMTP_PASSWORD")
GMAIL_SENDER = os.environ.get("GMAIL_SENDER")
ADMIN_EMAIL = os.environ.get("ADMIN_EMAIL", GMAIL_SENDER)

# PhonePe Payment Gateway Configuration
PHONEPE_MERCHANT_ID = os.environ.get("PHONEPE_MERCHANT_ID")
PHONEPE_CLIENT_ID = os.environ.get("PHONEPE_CLIENT_ID")
PHONEPE_CLIENT_SECRET = os.environ.get("PHONEPE_CLIENT_SECRET")
PHONEPE_ENVIRONMENT = os.environ.get("PHONEPE_ENVIRONMENT", "SANDBOX")  # SANDBOX or PRODUCTION


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cert_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cert_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

NEON_DB_URL = os.environ.get("NEON_DB_URL")

if NEON_DB_URL:
    # Use Neon Postgres when NEON_DB_URL is provided
    DATABASES = {
        "default": dj_database_url.parse(
            NEON_DB_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    # Fallback to local SQLite (development)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Frontend + CORS
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "http://localhost:5173")
CORS_ALLOW_ALL_ORIGINS = True
# If you decide to switch to CORS_ALLOWED_ORIGINS, remember to also enable credentials:
# CORS_ALLOWED_ORIGINS = [FRONTEND_BASE_URL]
# CORS_ALLOW_CREDENTIALS = True
