# Generated by Django 5.2.8 on 2025-11-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_certificate_course_certificate_orientation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='card_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='hero_image_url',
            field=models.URLField(blank=True),
        ),
    ]
