# Generated by Django 5.2.8 on 2025-11-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_certificate_types_course_class_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='playlist_modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
