# Generated by Django 4.2.7 on 2025-12-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='og_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_title',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
