# Generated by Django 5.2.8 on 2025-12-12 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_course_project_title_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('quote', models.TextField()),
                ('image', models.URLField(blank=True, help_text="URL to the testimonial author's image/avatar")),
                ('seo_title', models.CharField(blank=True, help_text="SEO title for this testimonial (e.g., 'Student Review: [Name] - [Course]')", max_length=180)),
                ('seo_description', models.CharField(blank=True, help_text='SEO description/meta description for this testimonial', max_length=320)),
                ('seo_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=320)),
                ('og_image_url', models.URLField(blank=True, help_text='Open Graph image URL for social media sharing')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this testimonial on the course page')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_entries', to='api.course')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
